// <auto-generated />
using System;
using CovidDataPortalApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovidDataPortalApi.Migrations
{
    [DbContext(typeof(CovidDataPortalDbContext))]
    [Migration("20220419090758_AncFieldAdded")]
    partial class AncFieldAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CovidDataPortalApi.Models.Domain.CasesClass", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<int?>("Anc")
                        .HasColumnType("int");

                    b.Property<int?>("Comorbid")
                        .HasColumnType("int");

                    b.Property<int?>("Contacts")
                        .HasColumnType("int");

                    b.Property<int?>("ContactsTraced")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Defence")
                        .HasColumnType("int");

                    b.Property<int?>("Gsp")
                        .HasColumnType("int");

                    b.Property<int?>("Inpatient")
                        .HasColumnType("int");

                    b.Property<int?>("PrePostProcedural")
                        .HasColumnType("int");

                    b.Property<int?>("Random")
                        .HasColumnType("int");

                    b.Property<int?>("Reinfection")
                        .HasColumnType("int");

                    b.Property<int?>("Symptomatic")
                        .HasColumnType("int");

                    b.Property<int?>("TotalDaysCases")
                        .HasColumnType("int");

                    b.Property<int?>("Traveller")
                        .HasColumnType("int");

                    b.Property<int?>("Untraced")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("casesClass");
                });

            modelBuilder.Entity("CovidDataPortalApi.Models.Domain.Deaths", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfAdmission")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("DaysAdmitted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaysAdmittedInICU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaysInOxygenSupportOrVentillator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaysTestedBeforeDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HospitalWhereAdmitted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SampleCollected")
                        .HasColumnType("datetime2");

                    b.Property<string>("SampleTestedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnderlyingCondition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaccinationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Deaths");
                });
#pragma warning restore 612, 618
        }
    }
}
